version: "3"
services:
  ngauthweb:
    build:
      dockerfile: "Dockerfile.dev"
    #image: ngauth_frontend
    container_name: ngauthfrontend
    ports: 
      - "4200:4200"
    volumes:
      - "/frontend/node_modules"
      - ".:/frontend"